apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api
  namespace: argo-cd
  labels:
    app: backend-api
spec:
  project: default
  source:
    repoURL: https://github.com/sarubhai/demo_cd.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=background
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
  info:
    - name: 'backend-api:'
      value: 'https://python-api.local/api/products'
